# AUTOGENERATED FROM 'project_site/user/queries/create_user.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateUserResult(NoPydanticValidation):
    id: uuid.UUID
    username: str
    email: str


async def create_user(
    executor: edgedb.AsyncIOExecutor,
    *,
    username: str,
    email: str,
    password: str,
) -> CreateUserResult:
    return await executor.query_single(
        """\
        select (
            insert User{
                username:=<str>$username,
                email:=<str>$email,
                password:=<str>$password
            }
        ){
            username,email
        };\
        """,
        username=username,
        email=email,
        password=password,
    )
