# AUTOGENERATED FROM 'project_site/user/queries/create_user.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateUserResult(NoPydanticValidation):
    id: uuid.UUID
    username: str
    email: str
    user_role: str


async def create_user(
    executor: edgedb.AsyncIOExecutor,
    *,
    username: str,
    email: str,
    password: str,
    user_role: str,
) -> CreateUserResult:
    return await executor.query_single(
        """\
        select (
            insert User{
                username:=<str>$username,
                email:=<str>$email,
                password:=<str>$password,
                user_role:=<str>$user_role,
            }
        ){
            username,email,user_role
        };\
        """,
        username=username,
        email=email,
        password=password,
        user_role=user_role,
    )
