# AUTOGENERATED FROM 'project_site/user/queries/get_user.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUserResult(NoPydanticValidation):
    id: uuid.UUID
    username: str
    email: str
    user_role: str


async def get_user(
    executor: edgedb.AsyncIOExecutor,
) -> list[GetUserResult]:
    return await executor.query(
        """\
        select  User {username,email,user_role}\
        """,
    )
