# AUTOGENERATED FROM 'project_site/product/queries/check_is_admin.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CheckIsAdminResult(NoPydanticValidation):
    id: uuid.UUID
    username: str
    email: str
    user_role: str


async def check_is_admin(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
) -> CheckIsAdminResult | None:
    return await executor.query_single(
        """\
        select
         User
        {id,
         username,
         email,
         user_role } 
        filter .id=<uuid>$user_id and .user_role=<str>"admin"\
        """,
        user_id=user_id,
    )
