# AUTOGENERATED FROM 'project_site/product/queries/create_category.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateCategoryResult(NoPydanticValidation):
    id: uuid.UUID
    name: str


async def create_category(
    executor: edgedb.AsyncIOExecutor,
    *,
    name: str,
) -> CreateCategoryResult:
    return await executor.query_single(
        """\
        select ( insert Category{
            name:=<str>$name
        }){
            name
        };\
        """,
        name=name,
    )
