# AUTOGENERATED FROM 'project_site/product/queries/delete_product.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations

import dataclasses
import datetime
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class DeleteProductResult(NoPydanticValidation):
    id: uuid.UUID
    title: str
    description: str | None
    price: float
    categories: list[DeleteProductResultCategoriesItem]
    created_at: datetime.datetime | None
    updated_at: datetime.datetime | None


@dataclasses.dataclass
class DeleteProductResultCategoriesItem(NoPydanticValidation):
    id: uuid.UUID


async def delete_product(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> DeleteProductResult | None:
    return await executor.query_single(
        """\
        select(
            delete Product filter.id=<uuid>$id
        )
        {
            title,description,price,categories,created_at,updated_at
        }\
        """,
        id=id,
    )
