# AUTOGENERATED FROM 'project_site/product/queries/delete_category.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class DeleteCategoryResult(NoPydanticValidation):
    id: uuid.UUID
    name: str


async def delete_category(
    executor: edgedb.AsyncIOExecutor,
    *,
    category_id: uuid.UUID,
) -> DeleteCategoryResult | None:
    return await executor.query_single(
        """\
        select(
            delete Category filter Category.id=<uuid>$category_id)
        {
           name
        }\
        """,
        category_id=category_id,
    )
