# AUTOGENERATED FROM 'project_site/product/queries/get_category_by_id.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetCategoryByIdResult(NoPydanticValidation):
    id: uuid.UUID
    name: str


async def get_category_by_id(
    executor: edgedb.AsyncIOExecutor,
    *,
    category_id: uuid.UUID,
) -> GetCategoryByIdResult | None:
    return await executor.query_single(
        """\
        select Category {name} filter Category.id=<uuid>$category_id\
        """,
        category_id=category_id,
    )
