# AUTOGENERATED FROM 'project_site/product/queries/get_category.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetCategoryResult(NoPydanticValidation):
    id: uuid.UUID
    name: str


async def get_category(
    executor: edgedb.AsyncIOExecutor,
) -> list[GetCategoryResult]:
    return await executor.query(
        """\
        select Category {name};\
        """,
    )
