# AUTOGENERATED FROM 'project_site/carts/queries/delete_cart.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class DeleteCartResult(NoPydanticValidation):
    id: uuid.UUID


async def delete_cart(
    executor: edgedb.AsyncIOExecutor,
    *,
    cart_id: uuid.UUID,
    user_id: uuid.UUID,
) -> DeleteCartResult | None:
    return await executor.query_single(
        """\
        delete 
        Cart filter .id=<uuid>$cart_id and .user.id=<uuid>$user_id;\
        """,
        cart_id=cart_id,
        user_id=user_id,
    )
