# AUTOGENERATED FROM 'project_site/carts/queries/get_cart_by_id.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetCartByIdResult(NoPydanticValidation):
    id: uuid.UUID
    user: GetCartByIdResultUser
    products: list[GetCartByIdResultProductsItem]
    quantity: int


@dataclasses.dataclass
class GetCartByIdResultProductsItem(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class GetCartByIdResultUser(NoPydanticValidation):
    id: uuid.UUID


async def get_cart_by_id(
    executor: edgedb.AsyncIOExecutor,
    *,
    cart_id: uuid.UUID,
) -> GetCartByIdResult | None:
    return await executor.query_single(
        """\
        select Cart {user,products,quantity} filter (Cart.id=<uuid>$cart_id);\
        """,
        cart_id=cart_id,
    )
