# AUTOGENERATED FROM 'project_site/carts/queries/get_cart.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetCartResult(NoPydanticValidation):
    id: uuid.UUID
    user: GetCartResultUser
    products: list[GetCartResultProductsItem]
    quantity: int


@dataclasses.dataclass
class GetCartResultProductsItem(NoPydanticValidation):
    id: uuid.UUID
    title: str


@dataclasses.dataclass
class GetCartResultUser(NoPydanticValidation):
    id: uuid.UUID
    username: str


async def get_cart(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
) -> list[GetCartResult]:
    return await executor.query(
        """\
        select Cart {user:{username},products:{title},quantity} filter .user.id=<uuid>$user_id;\
        """,
        user_id=user_id,
    )
